"""Remove relationships

Revision ID: 07d206b1853d
Revises: f1cdbcabdb77
Create Date: 2025-10-31 18:33:53.737992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07d206b1853d'
down_revision: Union[str, Sequence[str], None] = 'f1cdbcabdb77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cooking_tasks', 'status',
               existing_type=postgresql.ENUM('QUEUED', 'COOKING', 'READY', 'DELIVERING', 'DELIVERED', name='cookingstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cooking_tasks', 'status',
               existing_type=postgresql.ENUM('QUEUED', 'COOKING', 'READY', 'DELIVERING', 'DELIVERED', name='cookingstatus'),
               nullable=True)
    # ### end Alembic commands ###
