"""add payment_link to orders

Revision ID: 1d01a3cf21f7
Revises: c232d649ac37
Create Date: 2025-10-30 21:04:56.589060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1d01a3cf21f7'
down_revision: Union[str, Sequence[str], None] = 'c232d649ac37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_link', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_link')
    # ### end Alembic commands ###
