"""Add json data to demo

Revision ID: 5ad79c711b2f
Revises: 61d371fd62af
Create Date: 2025-09-13 09:36:00.022999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ad79c711b2f'
down_revision: Union[str, Sequence[str], None] = '61d371fd62af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demo', sa.Column('json_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demo', 'json_data')
    # ### end Alembic commands ###
