"""Fix order models and relationships

Revision ID: 7c463d4f6f28
Revises: 1d01a3cf21f7
Create Date: 2025-10-31 15:17:43.884064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c463d4f6f28'
down_revision: Union[str, Sequence[str], None] = '1d01a3cf21f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('orders_items')
    op.add_column('orders', sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('orders', 'place_id',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.drop_column('orders', 'trans_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('trans_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('orders', 'place_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('orders', 'transaction_id')
    op.create_table('orders_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('menu_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu.id'], name=op.f('orders_items_menu_item_id_fkey')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('orders_items_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_items_pkey'))
    )
    op.drop_table('order_items')
    # ### end Alembic commands ###
