"""add orders table

Revision ID: a0b49ada78ee
Revises: aeeb1e582a72
Create Date: 2025-10-24 23:38:56.008753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0b49ada78ee'
down_revision: Union[str, Sequence[str], None] = 'aeeb1e582a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('trans_id', sa.INTEGER(), nullable=True),
    sa.Column('payment_method', sa.Enum('CARD_ONLINE', 'CARD_TERMINAL', 'CASH', name='paymentmethod'), nullable=False),
    sa.Column('status', sa.Enum('WAITING_PAYMENT', 'PAID', 'COOKING', 'PARTIALLY_DELIVERED', 'COMPLETED', name='orderstatus'), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_items')
    op.drop_table('orders')
    # ### end Alembic commands ###
