"""Add cooking tasks table

Revision ID: c232d649ac37
Revises: a0b49ada78ee
Create Date: 2025-10-27 21:34:01.380654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c232d649ac37'
down_revision: Union[str, Sequence[str], None] = 'a0b49ada78ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooking_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'COOKING', 'READY', 'DELIVERING', 'DELIVERED', name='cookingstatus'), nullable=True),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cooking_tasks')
    # ### end Alembic commands ###
