"""Fix relationships

Revision ID: f2776f1024a9
Revises: c2223067c10d
Create Date: 2025-11-05 22:37:36.307540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f2776f1024a9'
down_revision: Union[str, Sequence[str], None] = 'c2223067c10d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('orders', sa.Column('payment_timeout_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_timeout_at')
    op.drop_column('orders', 'updated_at')
    # ### end Alembic commands ###
